scoreboard objectives remove maxheart
scoreboard objectives remove minheart
scoreboard objectives remove heart
scoreboard objectives remove status
scoreboard objectives remove player
tag @a remove dead
tag @a remove gained
tag @a remove player
tag @a remove joined